iotexproject/iotex-analytics

- .circleci/config.yml
- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/actions/protocol.go
- indexprotocol/actions/xrc20.go
- indexprotocol/actions/xrc20_test.go
- queryprotocol/actions/protocol.go
- testutil/blockbuilder.go
work on #48
example:
**query{
contract(address:"io14j96vg9pkx28htpgt2jx0tf3v9etpg4j9h384m",
numPerPage:10,page:19){
hash,
from,
to,
quantity,
timestamp,
}
}**
response：
{
"data": {
"contract": [
{
"hash": "e8f5dae0f8e8e8b33e563dcddecc3bb251bf5c782ad88e7c91376fab356f5560",
"from": "io1lkg0gxx4a79khszeawsshtng5tcax6v9dx8hna",
"to": "io1u642uwal6r4fuvu6fgkqn90e4ue66nl35w5gfj",
"quantity": "10000000000000000000",
"timestamp": "1561693390"
},
{
"hash": "b785a82ec56efc2a0a358a0d307f933985bd9f2b3977023b28a1a3bcc7138c86",
"from": "io1u642uwal6r4fuvu6fgkqn90e4ue66nl35w5gfj",
"to": "io1lkg0gxx4a79khszeawsshtng5tcax6v9dx8hna",
"quantity": "2504298239190483500",
"timestamp": "1561692990"
},
{
"hash": "6699806cefc579b1aa18b3635d2f3b674ea898f57d5795d5db60c3b8abea695e",
"from": …
> Index XRC-20 token transfer 48

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
- queryprotocol/actions/protocol_test.go
work on #73
**example:**
query{
xrc20(address:"io14j96vg9pkx28htpgt2jx0tf3v9etpg4j9h384m",
numPerPage:10,page:19){
hash,
from,
to,
quantity,
timestamp,
}
}
> Rename Contract to XRC20 in GraphQL 73

- indexprotocol/accounts/protocol.go
- indexprotocol/blocks/protocol.go
- indexprotocol/votings/protocol.go
> Partially Commit in a MySQL transaction 74

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
GetActionDetailByHash API
```
type Action {
byDates(startDate: Int!, endDate: Int!): ActionList
byHash(actHash: String!): ActionDetail
}
type ActionDetail{
actionInfo: ActionInfo
evmTransfers: [EvmTransfer]!
}
type EvmTransfer{
from: String!
to: String!
quantity: String!
}
```
> Add GetActionDetailByHash API

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
- queryprotocol/actions/protocol_test.go
work on #88 
**1、byAddress**
query{
xrc20{
byAddress(
address:"io1rxwu5wd24y2nf5t836uu7yky85p5f0pvquj59m",
numPerPage:10,page:1
){
exist,
xrc20{
contract,
hash,
from,
to,
quantity,
timestamp,
},
count,
}
}
}
**2、byPage**
query{
xrc20{
byPage(
numPerPage:10,page:1
){
exist,
xrc20{
contract,
hash,
from,
to,
quantity,
timestamp,
},
count,
}
}
}
> Add contract address to the Xrc20Info type 88

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/accounts/protocol.go
- queryprotocol/actions/protocol.go
work on #25 
add:
query{
topHolders(endEpochNumber:3,numberOfHolders:10){
address,balance
}
}
> Support top N holders 25

- graphql/generated.go
- graphql/models_gen.go
- graphql/schema.graphql
- queryprotocol/chainmeta/protocol.go
work on #59
**request:**
query{
chain{
mostRecentTPS(blockWindow:10)
}
}
**response:**
{
"data": {
"chain": {
"mostRecentTPS": 0.1
}
}
}
> tps should be float 59

- indexprotocol/accounts/protocol.go
> Account income is not correct 92

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
> Adding gasFee to ActionInfo type 99

- go.mod
- indexprotocol/blocks/protocol.go
- indexprotocol/votings/protocol.go
- indexprotocol/votings/protocol_test.go
Added nativeBucketOperator and merge it with calculated result
> Native staking

- indexprotocol/accounts/protocol.go
- indexprotocol/actions/protocol.go
- indexprotocol/actions/xrc20.go
- indexprotocol/blocks/protocol.go
- indexprotocol/rewards/protocol.go
- indexprotocol/votings/protocol.go
- queryprotocol/actions/protocol.go
- queryprotocol/chainmeta/chainmetautil/chainmetautil.go
- queryprotocol/chainmeta/protocol.go
- queryprotocol/productivity/protocol.go
- queryprotocol/rewards/protocol.go
- queryprotocol/votings/protocol.go
> Move all the SQL queries to constants and variables 93

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/votings/protocol.go
- queryprotocol/votings/protocol.go
implement APIs to query merged staking information 
the function is same as election 
getMeta
getCandidates
getBucketsByCandidate
> Native staking api

- graphql/generated.go
- graphql/schema.graphql
works on #114 
Fixed bucketInfo API pagination bug 
Query will be : 
```
{
delegate(startEpoch: 100, epochCount: 1, delegateName: "iosg"){
bucketInfo{
exist
bucketInfoList(pagination: {skip: 0, first: 10}){
epochNumber
count
bucketInfo{
voterAddress
votes
weightedVotes
remainingDuration
}
} 
}
}
}
```
> fix pagination bug

- indexprotocol/blocks/protocol.go
Because of time-out of the backoff function, changed it to ConstantBackOff
> change backoff function

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/votings/protocol.go
- queryprotocol/rewards/protocol.go
This reverts commit 43a14c34e8107848258bd7a24ddb1a52ba252b13.
> Revert "Unify address type in aggregate voting table (#121)"

- graphql/resolver.go
> add support daynamic params pagination

- indexprotocol/actions/protocol.go
- indexprotocol/blocks/protocol.go
> Create index on block_history and action_history table 130

- indexprotocol/votings/protocol.go
- queryprotocol/rewards/protocol.go
Added is_native column in aggregateVotingTable to distinguish between native vote and ethereum vote
Also, change reward query accordingly
This PR will be merged after rebuilding process is finished
> add is_native column in aggregateVotingTable and change reward query

- graphql/resolver.go
related to #145
https://github.com/iotexproject/iotex-analytics/pull/145#issuecomment-564242820
> change err msg

- graphql/generated.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/actions/protocol_test.go
- indexprotocol/actions/xrc20_test.go
- indexprotocol/blocks/protocol_test.go
- indexprotocol/rewards/protocol_test.go
- indexprotocol/votings/protocol_test.go
- queryprotocol/actions/protocol.go
- queryprotocol/actions/protocol_test.go
work on #147 and #149 
1、
```
query {
xrc20 {
byPage(pagination:{first:3,skip:1}) {
exist
count
xrc20 {
hash
from
to
quantity
timestamp
}
}
}
}
```
2、
```
query Xrc20Query($pagination:Pagination!) {
xrc20 {
byPage(pagination:$pagination) {
exist
count
xrc20 {
hash
from
to
quantity
timestamp
}
}
}
}
```
query variables:
```
{
"pagination":{
"first":3,
"skip":1
}
}
```
> get all tokens with pagination 147

- graphql/resolver.go
work on #153 
The max "first" value is 500
> bookkeeping api test failed in different writing 153

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/actions/xrc20.go
- queryprotocol/actions/protocol.go
- queryprotocol/actions/protocol_test.go
work on #152 
add a table to save holders's infos
```
query {
xrc20 {
tokenHolderAddresses(tokenAddress:"io14j96vg9pkx28htpgt2jx0tf3v9etpg4j9h384m") {
count
addresses(pagination:{first:2,skip:0})
}
}
}
```
count is the total holders's count
> get all addresses holder for an xrc20 token address 152

- indexprotocol/actions/protocol.go
- indexprotocol/actions/protocol_test.go
- indexprotocol/actions/xrc20.go
- indexprotocol/actions/xrc20_test.go
work on #162 
test good
check the following 4 funcs to make sure it's xrc20 contract:
//18160ddd -> totalSupply()
//70a08231 -> balanceOf(address)
//dd62ed3e -> allowance(address,address)
//095ea7b3 -> approve(address,uint256)
cannot use the following 2 funcs,because those return the same result as normal or not xrc20 contract:
//a9059cbb -> transfer(address,uint256)
//23b872dd -> transferFrom(address,address,uint256)
> Wrong token addresses appear in XRC20 holder information 162

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/actions/xrc20.go
- queryprotocol/actions/protocol.go
work on #156 
add table xrc721_history and xrc721_holders
> indexing XRC721 token 156

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
> rename xrc20 to xrc 166

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
work on #168
```
query {
action {
byType(type:"transfer") {
exist
count
actions(pagination:{first:30,skip:0}){
actHash
blkHash
actType
timeStamp
sender
recipient
amount
gasFee
}
}
}
}
```
supported type:
"grantReward", "putPollResult", "claimFromRewardingFund", "transfer", "execution"
> Filter action by type 168

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
work on #172
```
query {
account{
totalNumberOfHolders
}
}
```
> Create an API for TotalNumberOfHolders 172

- graphql/resolver.go
- queryprotocol/actions/protocol.go
> Adding total records field to Xrc20List response 170

- config.yaml
- indexprotocol/actions/hermes.go
- indexprotocol/actions/hermes_test.go
- indexprotocol/actions/protocol.go
- indexprotocol/actions/protocol_test.go
- indexprotocol/actions/xrc20_test.go
- indexservice/indexer.go
> insert into hermes_contract

- go.mod
- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/votings/probation.go
- indexprotocol/votings/protocol.go
- indexprotocol/votings/protocol_test.go
- queryprotocol/votings/protocol.go
> Rename Kickout to Probation 188

- queryprotocol/actions/protocol.go
> getCount can be simplified by using QueryRow 197

- indexprotocol/actions/protocol.go
action_history add blockheight index
related to #201
> action_history add blockheight index

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/actions/protocol.go
work on #173 
using:
```
query {
account{
totalAccountSupply
}
}
```
> Add an API for Total balance of all IoTeX accounts 173

- queryprotocol/actions/protocol.go
work on #184 
related api:
```
query {
action {
byType(type:"grantReward") {
exist
count
actions(pagination:{first:300,skip:0}){
actHash
blkHash
actType
timeStamp
sender
recipient
amount
gasFee
}
}
}
}
```
> Action byType issue 184

- queryprotocol/actions/protocol.go
> by address error

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/chainmeta/protocol.go
> Add an API for total token transferred

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/hermes2/protocol.go
work on #218
related api:
```
query {
hermes2(startEpoch:1576,epochCount:200){
byDelegate(delegateName:"xx"){
exist
count
totalRewardsDistributed
voterInfoList(pagination:{skip:0,first:10}){
fromEpoch
toEpoch
actionHash
timestamp
amount
voterAddress
}
}
}
}
query {
hermes2(startEpoch:1576,epochCount:200){
byVoter(voterAddress:"io1pcg2ja9krrhujpazswgz77ss46xgt88afqlk6y"){
exist
count
totalRewardsReceived
delegateInfoList(pagination:{skip:0,first:10}){
fromEpoch
toEpoch
actionHash
timestamp
amount
delegateName
}
}
}
}
query {
hermes2(startEpoch:1576,epochCount:200){
hermesMeta{
exist
numberOfDelegates
numberOfRecipients
totalRewardsDistributed
}
}
}
```
The combined query is supported:
```
query {
hermes2(startEpoch:1576,epochCount:200){
byDelegate(delegateName:"xx"){
exist …
```
> More APIs on Hermes2 218

- indexprotocol/votings/probation.go
- indexprotocol/votings/protocol.go
- indexprotocol/votings/protocol_test.go
- queryprotocol/rewards/protocol.go
fix inconsistency issue by filtering the voting result with probation list in voting protocol
> add probation filter logic into voting protocol

- graphql/resolver.go
- queryprotocol/hermes2/protocol.go
work on #221
request:
```
hermes2(startEpoch: 8717, epochCount: 1){
byDelegate(delegateName:"gamefantasy#"){
totalRewardsDistributed
}
}
```
response:
```
{
"data": {
"hermes2": {
"byDelegate": {
"totalRewardsDistributed": "0"
}
}
}
}
```
> Hermes2 should not return error if data does not exist 221

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/votings/probation.go
- indexprotocol/votings/protocol.go
- indexprotocol/votings/protocol_test.go
- queryprotocol/hermes2/protocol.go
- Updated graphql schema to support distributionRatio parameter
- Added logic to resolver to add ratioList for the delegate
- Added service method to fetch rewards ratio values for a delegate
> Delegate distribution ratio

- indexprotocol/votings/protocol.go
- indexprotocol/votings/stakingprotocol.go
- indexprotocol/votings/stakingprotocol_test.go
> encode delegate name patch

- indexservice/indexer.go
Added a nil pointer check condition code block to handle invalid chainEndPoint API, thus eliminating runtime error.
> Fix runtime error for invalid chainEndpoint API

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/votings/protocol.go
- queryprotocol/hermes2/protocol.go
- queryprotocol/rewards/protocol.go
work on #245 
have tested with api:
```
query{
hermes(startEpoch: 9550, epochCount:1, 
rewardAddress: "io12mgttmfa2ffn9uqvn0yn37f4nz43d248l2ga85",
waiverThreshold: 100) {
hermesDistribution{
delegateName
rewardDistribution{
voterIotexAddress
amount
}
}
}
}
query{
hermes2(startEpoch:10,epochCount:10){
byDelegate(delegateName:"ducapital"){
distributionRatio{
epochNumber
blockRewardRatio
epochRewardRatio
foundationBonusRatio
}
}
}
}
query{
voting(startEpoch: 1, epochCount: 10){
rewardSources(voterIotexAddress:
"io1mtkaz8w8mkzr9l7kg9fls4a4u6v8p4d6wltndx"){
exist
delegateDistributions{
delegateName
amount
}
}
}
}
```
> Delegate reward ratio should be Type Float64 245

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- indexprotocol/accounts/protocol.go
- indexservice/indexer.go
- queryprotocol/actions/protocol.go
- queryprotocol/chainmeta/protocol.go
Add total supply and total circulating supply API
> Add total supply and total circulating supply API ISSUES #249

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolver.go
- graphql/schema.graphql
- queryprotocol/chainmeta/protocol.go
add query field totalCirculatingSupplyNoRewardPool
> add query field totalCirculatingSupplyNoRewardPool

- config.yaml
- indexprotocol/actions/protocol_test.go
- indexprotocol/actions/xrc20_test.go
- indexprotocol/protocol.go
- indexservice/indexer.go
- queryprotocol/hermes2/protocol.go
Change HermesConfig.MultisendContractAddress to a list rather than a single address #254
> Change HermesConfig.MultisendContractAddress to list

- queryprotocol/hermes2/protocol.go
fix bug for the value of the query statement is enclosed in quotation marks
> fix bug for change hermes config

- queryprotocol/rewards/protocol.go
> fix hermes average stat bug

- queryprotocol/actions/protocol.go
1. Improve query
2. Disable the GetActionsByType for now
> return nil for actions by type query

- sql/storebase.go
max connections to 400
max idle connections to 10
max lifetime to 5m
> set sql connections

- config.yaml
- indexservice/indexer.go
- main.go
- testutil/blockbuilder.go
> Add logger, api stats
